DATALOADER:
  batch_size: 32
  poison_path: './runs/ce_em_gen'
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: ce_em_eval
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: EM
TRAIN:
  num_epochs: 200