#import pointnet2_ops.pointnet2_modules
#import pointnet2_ops.pointnet2_utils
#from pointnet2_ops._version import __version__

import PCT_Pytorch.pointnet2_ops_lib.pointnet2_ops.pointnet2_modules
import PCT_Pytorch.pointnet2_ops_lib.pointnet2_ops.pointnet2_utils
from PCT_Pytorch.pointnet2_ops_lib.pointnet2_ops._version import __version__
