DATALOADER:
  batch_size: 32
  poison_path: './runs/intra_fc_em_gen'
  poison_gen: None
EXP:
  DATASET: medpt
  EXP_ID: intra_fc_em_eval
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: FC_EM
TRAIN:
  num_epochs: 200