DATALOADER:
  batch_size: 32
  poison_path: './runs/reg_ap_t_gen'
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: reg_ap_t_eval
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: REG_AP_T
TRAIN:
  num_epochs: 200