DATALOADER:
  batch_size: 32
  poison_path: None
  poison_gen: standard
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: reg_ap_gen
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls
  poison_type: REG_AP
TRAIN:
  num_epochs: 100
AUG:
  NAME: chamf_pgd
POISON: REG_AP