DATALOADER:
  batch_size: 128
  poison_path: None
  poison_gen: standard
EXP:
  DATASET: scanobjectnn
  EXP_ID: scan_fc_em_gen
  LOSS_NAME: chamf_standard_ce
  MODEL_NAME: pointnet
  TASK: cls
  poison_type: FC_EM
TRAIN:
  num_epochs: 200
AUG:
  NAME: chamf_standard_fc_pgd
EXP_EXTRA:
  get_feature: default
POISON: FC_EM