DATALOADER:
  batch_size: 32
  poison_path: './runs/ce_ap_gen'
  poison_gen: None
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: ce_ap_eval
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: AP
TRAIN:
  num_epochs: 200