DATALOADER:
  batch_size: 32
  poison_path: {custom poison path}
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: mixup_defense
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: custom
TRAIN:
  num_epochs: 200
AUG:
  NAME: mixup