DATALOADER:
  batch_size: 32
  poison_path: './runs/fc_em_gen'
EXP:
  DATASET: modelnet40_dgcnn
  EXP_ID: fc_em_eval
  LOSS_NAME: cross_entropy
  MODEL_NAME: pointnet
  TASK: cls_trans
  poison_type: FC_EM_thre
TRAIN:
  num_epochs: 200